### PR TITLE
Bugfix/security update packages

### PR DESCRIPTION
**Pull request by nickpreston24**

### CODE REVIEW

**Review by Harvest-Haven-Apps — APPROVED** [review]
Braden: Just be wary about what we choose to update. Some things like File2Html need to stay on a certain version which depends on older dependencies like Bluebird. Other than that most everything can 'usually' be updated.

**Comment by Harvest-Haven-Apps** [comment]
Braden: Build failed on Netlify because when you updated ```draft-js-link-plugin```, it added another dependency which didn't exist: ```union-class-names```

**Comment by Harvest-Haven-Apps** [comment]
Braden: @MikePreston17, Ok I fixed it with a hotfix and it deploys now correctly. Please ask me next time before we do dependency upgrades. I am fine with updating them, but I think we should do them a few at a time by hand. This will look a bit better too when we clear out the ones we flat out just don't need. If you want, I can start up a list of what I know needs to go.

**Comment by nickpreston24** [comment]
Thanks, will do.

**Pull request merged**
